[phases.setup]
nixPkgs = ["...", "(python3.withPackages (ps: with ps; [ opencv4 numpy ]))", "libGL", "glib"]

[phases.install]
cmds = ["npm install --ignore-scripts"]

[start]
cmd = "node virtual-tradeshow-commercial-v1/app_build/server/index.js"
